### PR TITLE
completed the SportsTracker

### PR DESCRIPTION
**Pull request by ukpagrace**

### CODE REVIEW

**Comment by stevietv** [comment]
Hi @ukpagrace - currently the program won't run as there is no `appsettings.json` file
You're going to need to provide a (cleaned) version of this in the repo.

**Review by stevietv — CHANGES_REQUESTED** [review]
add `appsettings.json`

**Comment by ukpagrace** [comment]
Alright I would do that 
Thanks

**Comment by ukpagrace** [comment]
Hey @stevietv 
My appsettings.json file contains my credentials for the email logger.

**Comment by stevietv** [comment]
So make them blank before you commit it. commit only a template for the appsettings.json
this is how I did it: https://github.com/TheCSharpAcademy/CodeReviews.Console.SportsResults/blob/main/SportsResults.StevieTV/SportsResults.StevieTV/appsettings.json

**Comment by ukpagrace** [comment]
Done.

**Comment by stevietv** [comment]
thanks for doing that., it all works!

image

good work. Next time I would recommend also putting the Port and the EnableSSL options in the appsettings, My local mail server for testing has a different port to the hardcoded 587 in your code.

**Comment by ukpagrace** [comment]
Noted, Thank you

**Pull request merged**
