### PR TITLE
Finished project

### PR DESCRIPTION
**Pull request by JsPeanut**

### CODE REVIEW

**Comment by kimfom01** [comment]
@JsPeanut is this project submitted on the academy's website?

**Comment by JsPeanut** [comment]
> @JsPeanut is this project submitted on the academy's website?

Hey there. Yes, it is.

**Comment by kimfom01** [comment]
Honestly I can't find it on my dashboard... maybe someone else already picked it up but hasn't come to review it yet. I'm so sorry about this misunderstanding and I will ask @TheCSharpAcademy to investigate this :hand_over_mouth: it's been 7 months since you submitted :exploding_head:

**Comment by JsPeanut** [comment]
> Honestly I can't find it on my dashboard... maybe someone else already picked it up but hasn't come to review it yet. I'm so sorry about this misunderstanding and I will ask @TheCSharpAcademy to investigate this :hand_over_mouth: it's been 7 months since you submitted :exploding_head: 

I think it has already been reviewed by Pablo, but I asked him to delete the previous fork, that might be why. Thank you though!!

**Comment by kimfom01** [comment]
Ahh my bad :sweat_smile:

**Pull request closed without merging**
